---
title: "Assignment 2: R Basics and Exploratory Data Analysis"
author: "WenLi"
date: "9/4/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# **1. College Data Analysis**

```{r College, fig.width=4.5, fig.height=3, fig.align = 'left', message=FALSE, warning=FALSE}
library(ggplot2)

##### a. Read the data into R.
College = read.csv("College.csv", header = TRUE)

##### b. Find the median cost of books.
median(College$ Books)

##### c. Produce a scatterplot showing relationship between Apps and Accept.
ggplot(data=College, aes(x=Apps, y=Accept)) + geom_point() + geom_smooth() +
       labs(title="Relationship between Apps and Accept", 
            x="#application", y="#accept") +
       theme(plot.title = element_text(hjust = 0.5)) 

##### d. Showing the overall enrollment numbers (P.Undergrad plus F.Undergrad)
ggplot(College, aes(x = P.Undergrad+F.Undergrad, fill = Private)) + 
      geom_histogram(bins = 15, position = "dodge") +
      labs(title="Overall enrollment numbers of shcools", 
           x="#undergraduates", y="#school") +
      theme(plot.title = element_text(hjust = 0.5)) 

##### e. Schools'acceptance rates for each of the two Top categories
Top <- as.factor(ifelse(College$Top10perc > 75, "Yes", "No"))
summary(Top)
AccRate = College$Accept / College$Apps
ggplot(College, aes(x = AccRate, fill = Top)) + 
      geom_histogram(bins = 15, position = "dodge") +
      labs(title="Acceptance rates for top schools and others", 
           x="acceptance rates", y="#school") +
      theme(plot.title = element_text(hjust = 0.5))

cat ("The number of top universities is ", sum(College$Top10perc > 75))

##### f. Two new plots of any type,

# Colleges that have the most students from top 10% of high school class
# usually have better graduation rate but do not obtain the highest graduation rate.
ggplot(data=College, aes(x=Top10perc, y=Grad.Rate)) + geom_point() + geom_smooth() +
       labs(title="Relationship between Top10perc and Grad.Rate", 
            x="top10 percentage", y="graduation rate") +
       theme(plot.title = element_text(hjust = 0.5))

#Universities with various acceptance rates seem to have very close book cost.
ggplot(data=College, aes(x=AccRate, y=Books)) + geom_point() + geom_smooth() +
       labs(title="Relationship between acceptance rate and book cost", 
            x="acceptance rate", y="book cost") +
       theme(plot.title = element_text(hjust = 0.5))

```


# **2. Auto Data Analysis**

```{r Auto, fig.width=5, fig.height=3, fig.align = 'center', message=FALSE, warning=FALSE}
library(ggplot2)
library (PerformanceAnalytics)

##### Read the data into R.
Auto = read.csv("Auto.csv", header = TRUE, na.strings = "?")
Auto = na.omit(Auto)
dim(Auto)
##### a. Specify which of the predictors are quantitative, and which are qualitative?
# Quantitative: mpg	cylinders	displacement	horsepower	weight	acceleration	year.
QuantitativePredictors = c("mpg", "cylinders", "displacement", "horsepower", 
                           "weight", "acceleration", "year")
# Translate origin into factor
Auto$originFactor = factor(Auto$origin, labels = c("USA", "Germany", "Japan"))
table(Auto$originFactor, Auto$origin)
# Qualitative:  name origin originFactor
QualitativePredictors = c("name", "origin", "originFactor")

##### b. What is the range, mean and standard deviation of each quantitative predictor?
Quantitatives = which(names(Auto) %in% QuantitativePredictors)
sapply(Auto[, Quantitatives], range)
sapply(Auto[, Quantitatives], mean)
sapply(Auto[, Quantitatives], sd)


##### c. Now remove the 40th through 80th (inclusive) observations from the dataset. 
#####    What is the range, mean, and standard deviation of each predictor in the 
#####    subset of the data that remains?
sapply(Auto[-seq(40, 80), Quantitatives], range)
sapply(Auto[-seq(40, 80), Quantitatives], mean)
sapply(Auto[-seq(40, 80), Quantitatives], sd)

##### d. Using the full data set, investigate the predictors graphically, using 
#####    scatterplots,correlation scores or other tools of your choice. Create 
#####    a correlation matrix for the relevant variables.
chart.Correlation(Auto[, Quantitatives], histogram=TRUE, pch=19)
Matrix = cor(Auto[, Quantitatives])
round(Matrix, 2)
##### e. Suppose that we wish to predict gas mileage (mpg) on the basis of the 
#####    other variables. Which, if any, of the other variables might be useful 
#####    in predicting mpg? Justify your answer based on the prior correlations.

#From the correlation graph, we can find that all of the quantitative variables show some 
# correlation with mpg. for example, as weight goes up, mpg goes down.
ggplot(data=Auto, aes(x=weight, y=mpg)) + geom_point() + geom_smooth() +
       labs(title="Relationship between mpg and weight", 
            x="weight", y="mpg") +
       theme(plot.title = element_text(hjust = 0.5)) 
# and better acceleration with higher mpg 
ggplot(data=Auto, aes(x=acceleration, y=mpg)) + geom_point() + geom_smooth() +
       labs(title="Relationship between mpg and acceleration", 
            x="acceleration", y="mpg") +
       theme(plot.title = element_text(hjust = 0.5)) 


```
